### ISSUE TITLE
Please make a progress bar.

### ISSUE THREAD

**Issue by L4cache** [zeroepoch/plotbitrate#10]
I know it's mostly useless, but at least it can provide psychological comfort. :p

**Comment by L4cache** [comment]
After read your code, I'm thinking we can get PTS from output, which can be "present position". But I don't know how to get duration (i know where but don't know how... sorry for my bad python knowledge).

**Comment by L4cache** [comment]
And thanks for this highly useful tool!

**Comment by zeroepoch** [comment]
Are you suggesting as it's running to have an option to print the percentage as a function of duration?  Such as 10 minutes into a 2 hour video and it would print something like 8%?

**Comment by L4cache** [comment]
Yes, that's what I mean. Thanks for replying.

**Comment by zeroepoch** [comment]
That shouldn't be too hard to add.  I've been pretty busy lately with work so it might take a while to get that feature added.

**Comment by L4cache** [comment]
Appreciate it.

**Comment by zeroepoch** [comment]
Give the new `-p` option a try and let me know how it goes.

**Comment by L4cache** [comment]
It goes very well.
