### ISSUE TITLE
SyntaxError: invalid syntax in file "plotbitrate.py", line 226

### ISSUE THREAD

**Issue by aphex3k** [zeroepoch/plotbitrate#11]
```
File "plotbitrate.py", line 226
    print(flush=True)
               ^
SyntaxError: invalid syntax
```
Python 2.7.16

**Comment by zeroepoch** [comment]
The script only supports python 3.  You can check that the first line in the script is `#!/usr/bin/env python3`.  Also python 2 is now officially EOL as of 1/1/2020, so it doesn't make sense to add support for python 2.  Sorry, I would suggest switching to python 3 if that's an option for you.
