### ISSUE TITLE
Monolithic bitrate viewer for video

### ISSUE THREAD

**Issue by ghost** [zeroepoch/plotbitrate#12]
Please make it possible to view video bitrate in one graph, without separating into IPB, like in the BitrateViewer app https://www.videohelp.com/software/Bitrate-Viewer-2
I think IPB graph is less important.

**Comment by zeroepoch** [comment]
A video is made up of a sequence of different types of frames. A [GOP](https://en.wikipedia.org/wiki/Group_of_pictures) is a set of frames from one infra (reference) frame to another infra frame. Something like IBBBBPBBBBPBBBBI. What you're seeing in the graph is the actual bitrate over time. If you ignore the colors that's what you would get. "B" and "P" frames are much smaller than "I" frames, so they look like different graphs on top of each other, but timewise they are all interleaved. Maybe what you are asking for is for the sum of each GOP to be a single pulse on the graph? That would be a fundamentally different way to process the data than what I'm doing now. Unfortunately I don't have time these days to add new features to this script such as this.

**Comment by ghost** [comment]
I know about GOP.

> Maybe what you are asking for is for the sum of each GOP to be a single pulse on the graph?

Something like that. Single videobitrate/time graph. BitrateViewer for example averages every 1 second.

I agree that showing IBP graph can be helpful. But I knew other programs for showing bitrate (MPEG2, DVD), ALL showed the general bitrate. This information is more useful and interesting to the user than separate bitrate. This allows to see compliance with the DVD specification (10800 kbps max). Your script shows peaks up to 19000. I hope you find time to implement this functionality.

By the way, I noticed BitratViewer is much faster. Your script does full decoding. BitrateViewer does not, but works less accurately.

**Comment by zeroepoch** [comment]
`plotbitrate.py` is a simple python script and other then streaming the XML from ffmpeg it doesn't do any optimizations. It is faster than the perl script I based it on; I wrote this script because I didn't want to wait all day. I think BitrateViewer is written in C++ or some compiled language and maybe uses ffmpeg directly, which would make it much faster. You could maybe hack the code to dump the data as CSV and use excel or something to plot it.

I've only used the script maybe a dozen times myself and my original goal was to verify that denoise was helping to reduce bitrate by knowing where the bitrate was high and checking it again post re-encoding. I've made a few minor changes here and there to fix a bug or for a quick request, but haven't really been doing much with it anymore. I actually find it interesting that this is one of my most starred projects since it was one of my shorter projects :smile:

**Comment by ghost** [comment]
Your project gave a unique opportunity to view bitrate of audio formats. As well as new video formats: H.265, VP9, AV1. Mostly I use it for audio and have advised in some forums.

**Comment by zeroepoch** [comment]
@denismn, there have been a number of forks of this repo at this point and maybe one of them has some interesting changes for you. I want to say one of them added some data dumping options, but I don't exactly remember. I did use my script at one point to compare bitrates between DTS and AC3 to see how much bandwidth it consumes over time. I almost forgot it can do that, haha.

**Comment by zeroepoch** [comment]
I went to take a look at the forks and @rezun has made a ton of improvements to my script. I think it supports what you're requesting and he's using multithreading (which I didn't know ffprobe supported) so it's much faster. I did a quick check on Avenger's End Game which is 3 hours and it could process the entire movie in just a few minutes. The perl version I found online before I started this project would have taken maybe 8 hours. His script is maybe 5x or 10x faster than even my script! See https://github.com/rezun/plotbitrate

**Comment by ghost** [comment]
> rezun plotbitrate

Unfortunately, error appears
```
SyntaxError: invalid syntax line 70
time: float
```
I use Ubuntu 16.04, maybe that's why. I just copied plotbitrate.py to ~/.local/bin and chmod +x. Dependencies seem to be installed.

**Comment by rezun** [comment]
My bad. I forgot to mention a dependency for python 3.6 which is "dataclasses".
The best way to install my version is by using pip (pip install rezun-plotbitrate).
For your case, you can just install dataclasses and it should work.

I'm in talks with zeroepoch to merge my changes back and create a canonical version that's just called plotbitrate. But I haven't had the time to do that yet.

**Comment by ghost** [comment]
Pip gives an error. Unfortunately, Ubuntu 16.04 has too old Python version 3.5. I installed Python 3.8 from PPA, but it doesn't find the Matplotlib module, and Pip is not available for it. I have a portable Python in Wine, but I couldn't connect the Pip module to it. I give up. Maybe I will install Arch Linux in dualboot.

By the way, have you tried installing your script on Windows? Maybe you share a portable x86 build? For Wine.

**Comment by ghost** [comment]
> portable Python in Wine

Standalone Python installation works in Wine. Thanks. I noticed that your app shows more average audio bitrate.

To reduce the contamination of Wine's registry, I did:
1. copy ~/.wine to ~/.wine.bak
2. winecfg change OS to Windows 7 (need for Python installer)
3. install python-3.8.2.exe from https://www.python.org/downloads/release/python-382/ or newer (Windows x86 executable installer) to c:\python, check box "Add to PATH" during installation
4. wine python -m pip install -U matplotlib
5. wine python -m pip install -U dataclasses
6. wine python -m pip install -U rezun-plotbitrate
7. put ffprobe.exe from https://rwijnsma.home.xs4all.nl/files/ffmpeg/?C=M;O=D (static) to C:\windows or C:\windows\system32\WindowsPowerShell\v1.0 (taken from official ffmpeg forum https://ffmpeg.zeranoe.com/forum/viewtopic.php?f=3&t=6930 ), this build supports AV1 format.
8. wine python -m plotbitrate "y:\input.mkv" (run for testing)
9. wineserver -k (kill all wine processes)
10. rename ~/.wine to ~/.wine.new
11. rename ~/.wine.bak to ~/.wine (restore clear wine)
12. winecfg change OS to Windows XP
13. copy c:\python from ~/.wine.new to ~/.wine (no need to copy winregistry)
14. wine regedit, open HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment, doubleclick PATH, add ;C:\python
15. wine python -m plotbitrate "y:\input.mkv" (run for testing) or wine "c:\python\python.exe" -m plotbitrate "y:\input.mkv" or wine c:/python/python -m plotbitrate "y:\input.mkv" (if p14 has not been made)
16. remove ~/.wine.new

Wine registry stays clean (except if python will create something during startup). Size of C:\python folder only 325 MB. However, the folder contains 14000 files! Checked in wine-staging 5.7

**Comment by zeroepoch** [comment]
@denismn I don't know if being able to run in Windows is a requirement, but it it might be a lot simpler (and less contamination) to use a docker container. You could use latest Arch, Fedora 32, Ubuntu 20.04, etc. which should all have a recent ffmpeg and python 3.7+. I ran @rezun's script on my native Fedora 31 install which has python 3.7 and I was able to test it on a few files. I didn't try the pip version I just ran the script directly. I already had all the other dependencies installed via the package manager.

**Comment by rezun** [comment]
So. This is totally out of scope of this issue but I have no way of contacting you @denismn 
Looking at currently supported distros and their shipping version of python, I think it's a good idea to make my version compatible with python 3.5 as it's still around, before merging it back into this repo not to break any existing installations.
So, I've released a preview version (on my master branch). Can you please confirm, that it's working for you?
It's also available via pypi where you have to explicitly state the version: `pip install rezun-plotbitrate==1.1.0a1`
Please test it and contact me at azcane@gmail.com to let me know if it works or if you have any issues.

**Comment by ghost** [comment]
Not working, sorry.
```
python3 -m pip install -U pip
python3 -m pip install rezun-plotbitrate==1.1.0a1
```
Error building local dependency (PyQt5-5.14.2).
I had to explicitly specify python3, otherwise python2 was used.
The system package of PyQt5 has version 5.5.1, but it is too old and therefore not used, as I understand it.
Ubuntu Xenial is too old. I don't like Python, it creates too many files.

**Comment by zeroepoch** [comment]
@denismn since the feature request specified in this issue is now resolved (the changes from @rezun's branch are now part of this repo) I think we can close this issue now. If you are able to install the required python modules manually then you can just clone and run the script directly. I believe older versions of the python modules defined in `requirements.txt` will work, but we've only tested with the latest.
