### ISSUE TITLE
Per-frame bitrate graph?

### ISSUE THREAD

**Issue by andreymal** [zeroepoch/plotbitrate#14]
The old version of plotbitrate ([4553220](https://github.com/zeroepoch/plotbitrate/tree/4553220ed5132503c0dda777bcc41b83ec866004)) painted the bitrate for each frame separately. Although I-frames usually have extremely high bitrate, I find this this graph a lot more informative because it allows me to analyze videos in more detail - such a graph shows well number of B-frames, GOP size, scenecuts and other small details. Unfortunately, I didn't find the same mode in the new version, and if it really does not exist, then it would be good if it appeared again :)

(Oh, it seems this issue is an opposite of #12 :)

[![](https://i.imgur.com/V27y5WFm.png)](https://i.imgur.com/V27y5WF.png)

**Comment by zeroepoch** [comment]
@rezun already added this option in the latest script. Try using the `-t` option and see if that fits your needs.

**Comment by andreymal** [comment]
Unfortunately `plotbitrate -t video.mp4` still does not draw per-frame graph

[![](https://i.imgur.com/Q5mU8v0m.png)](https://i.imgur.com/Q5mU8v0.png)

**Comment by zeroepoch** [comment]
Oh... sorry, you meant per-frame not per-frame-type. @rezun and I had a discussion about this when we did some major refactoring and most people were expecting the "average" bitrate per/sec rather than "instantaneous" bitrate/sec. The way frame sizes are aggregated now it would be difficult to implement this as an option without having two different code paths. As a short term solution it might be better to use a previous version of the script. Or if you're fine messing with Excel or another plotting tool you can use the `-f csv_raw -o out.csv` options to save the frame data as a CSV file and play with it from there. If you want a version before these changes, but with threading speed ups try 5ceee64128c59f164ec83781f4766ae88f98b057.

**Comment by rezun** [comment]
Well. I think in most cases the bitrate per second is what people would like to know. I don't have a use case to go by frame but I see how it could be useful and this is a regression. I don't think it would be *too* much effort to have this as an additional option again. But, painting these separate graphs does take significantly more time. So this option would only be feasible with shorter videos or a time restriction.
I'll take a look at it and see what I can do in the next days.

**Comment by fa1rid** [comment]
Is the bitrate shown the average per second or the maximum?

**Comment by fa1rid** [comment]
>  Or if you're fine messing with Excel or another plotting tool you can use the `-f csv_raw -o out.csv` options to save the frame data as a CSV file and play with it from there

for csv option, the size is in which unit?

**Comment by fa1rid** [comment]
does this tool work properly with variable frame rate?

**Comment by zeroepoch** [comment]
> Is the bitrate shown the average per second or the maximum?

The tool currently shows the average bitrate per second.

> for csv option, the size is in which unit?

It's in bytes. It shows the size in bytes of each individual frame.

> does this tool work properly with variable frame rate?

Yes, this tool properly supports variable frame rate now.

**Comment by zeroepoch** [comment]
Closing out this old issue assuming the suggested workarounds help solve the problem.

**Comment by andreymal** [comment]
Well, I'm still not very happy with getting stuck on the old version

**Comment by zeroepoch** [comment]
@andreymal, I fixed up the CSV handling a bit and added an example to the README.md that shows how to use the CSV output with `gnuplot` to get something like before. After updating to 1.1.1.0 take a look at the instructions in the README, also shown at https://pypi.org/project/plotbitrate/1.1.1.0/.

Here's an example of what the output looks like on my system with Fedora 37.
![image](https://github.com/zeroepoch/plotbitrate/assets/1310250/02c223dd-bacc-4219-962e-74621829a011)
