### ISSUE TITLE
ImportError: Cannot load backend 'Qt5Agg' which requires the 'qt5' interactive framework, as 'headless' is currently running

### ISSUE THREAD

**Issue by itssoap** [zeroepoch/plotbitrate#15]
![image](https://user-images.githubusercontent.com/6275744/101244888-09108400-372f-11eb-87cc-c8647b96bf0c.png)
Hi! I was trying to run plotbitrate on WSL2 on Windows 10 and ran over "Error: Missing package 'python3-matplotlib'". After checking the exception handling in code, I tried to import modules on python and run it, to encounter the main issue. As I am unaware of the issue, can you please give some input regarding the same. Thanks.

**Comment by rezun** [comment]
I'm sorry but running plotbitrate under WSL2 is currently not a supported use case.
It's quite the hassle as you'd have to install an XServer on your windows host machine and configure it correctly. I didn't get it to work properly even with TK as the backend and this guide: https://medium.com/@shaoyenyu/make-matplotlib-works-correctly-with-x-server-in-wsl2-9d9928b4e36a
I'd recommend installing the windows version of python and using plotbitrate via powershell or CMD

**Comment by rezun** [comment]
Following these instructions I got it working with TK: https://stackoverflow.com/questions/61110603/how-to-set-up-working-x11-forwarding-on-wsl2
I've added a fall back to TK for this case in PR #16 
If @zeroepoch is ok with this approach, I'll release a new version

**Comment by rezun** [comment]
@Soaibkhan38 
I've published the new version 1.0.7.2 with the Tk fallback.
Please follow my last link on how to setup GUI capabilities in WSL 2 or use the windows version of python to install plotbitrate.
