### ISSUE TITLE
AttributeError: 'module' object has no attribute 'which'

### ISSUE THREAD

**Issue by redgrasss** [zeroepoch/plotbitrate#2]
Hello,

I have to admit I am not familiar with Python.
I use Anacaonda distribution (Python Version: 2.7.9) on Windows 7 and placed your script in ffmpeg directory. When I try to use it I got this error:
[...]
n\plotbitrate.py", line 51, in <module>
    if not shutil.which("ffprobe"):
AttributeError: 'module' object has no attribute 'which'

Thanks a lot in advance for your help!!

**Comment by zeroepoch** [comment]
Unfortunately the shutil.which method only exists in Python 3.3+.  In an effort to modernize the script from the beginning I started with Python 3.  I'm not sure what it would take to get the script to work with Python 2, but from a quick Google search there is not a simple one line change to replace the shutil.which call.

**Comment by redgrasss** [comment]
Thanks! That helped!

Great tool!!
