### ISSUE TITLE
Cannot plot for files that start at time != 0

### ISSUE THREAD

**Issue by JamesGKent** [zeroepoch/plotbitrate#20]
some files such as transport stream may start at a time other than zero.
currently this tool correctly gets the duration, but because the iterator starts at t=0, the plot is always empty and shows peak and mean of 0 bitrate. this also means the calculation in the progress reporting is incorrect on these files.
Will open a pull request shortly.

**Comment by zeroepoch** [comment]
Thanks for the contribution. I left a few minor comments on the PR.

**Comment by JamesGKent** [comment]
I've left a comment regarding the output of the files I have and how some of them are created.
I've also made another branch where I have added the ability to differentiate between key and non key frames and also tweaked the location of the key so it doesn't overlap the plot (its above the plot next to the heading) would this be something you're interested in merging?

**Comment by zeroepoch** [comment]
Sure. If you don't mind creating a pull request we can take a look.

**Comment by zeroepoch** [comment]
I'm going to close this issue since the change has been merged in. We can open a new PR or issue for tracking the other enhancements you mentioned.
