### ISSUE TITLE
ability to specify `ffprobe` path

### ISSUE THREAD

**Issue by ccoenen** [zeroepoch/plotbitrate#31]
I don't have ffprobe on my path, I would like to be able to specify its location somehow. It would be ok as a parameter or an environment variable or a config file. I think this would also be useful in cases where people keep different versions of ffmpeg around.

**Comment by zeroepoch** [comment]
I just released version 1.1.3.0 which has your change included. Thanks @ccoenen for your contribution!

**Comment by ccoenen** [comment]
thank you so much :-)
