### ISSUE TITLE
TypeError float argument

### ISSUE THREAD

**Issue by jiggunjer** [zeroepoch/plotbitrate#5]
I'm new to python, but I thought I'd give your script a try. Using the basic command "plotbitrate.py Wildlife.mwv" gives an error in `line 151 frame_time = float(node.get('pkt_pts_time'))` which says `TypeError: float() argument must be a string or a number, not 'NoneType'`. 

I have the latest Zeranoe build (x64 Windows 7) of ffmpeg in my path. FFprobe seems to read the default video file without problems, but I have no experience with processing xml. Is this a problem with my video source, ffprobe or the python script? Using python 3.5.

**Comment by jiggunjer** [comment]
I found that ffprobe does not produce xml fields with the `pkt_pts_time` attribute. Might need to change the ffprobe switch, I'll try to decipher the poor FFMPEG documentation.

**Comment by zeroepoch** [comment]
You're right it needs to have the `pkt_duration_time` field for it to work.  You need a fairly recent version of ffmpeg/ffprobe for this field to be present.  Don't remember which version added it, but probably want 2.0 or newer to be safe.

**Comment by jiggunjer** [comment]
I think the Zeranoe versions are very up-to-date. Their version info is weird, but two years ago they were already using ffmpeg 2.4. So my december 2015 build should be good. I notices the xml does have a `dts version instead of pts` field--except for the last frame, which lacks some fields.

example frame:
`<frame media_type="video" stream_index="1" key_frame="0" pkt_dts="29896" pkt_dts_time="29.896000" best_effort_timestamp="29896" best_effort_timestamp_time="29.896000" pkt_duration="33" pkt_duration_time="0.033000" pkt_pos="25989730" pkt_size="24681" width="1280" height="720" pix_fmt="yuv420p" pict_type="P" coded_picture_number="895" display_picture_number="0" interlaced_frame="0" top_field_first="0" repeat_pict="0"/>`

It is the standard windows 7 video file (901 frames in VC1 format).

**Comment by jiggunjer** [comment]
my fix for line 151 (I just don't have `pkt_pts_time` values on my frames, or ffprobe isn't seeing them):

```
try:
            frame_time = float(node.get('best_effort_timestamp_time'))
        except:
            try:
                frame_time += float(node.get('pkt_duration_time'))
            except:
                frame_time = float(node.get('pkt_pts_time')) #3rd and final try to get time
```

Works now, thanks!
I might update the algorithm in the future, because your calculation of bitrate is a bit simplistic. Good practice for a novice like me though :D

**Comment by zeroepoch** [comment]
I think using `pkt_duration_time` each time rather than framerate would be better.  It would account for variable framerate which is becoming more common now.  As you noted to avoid the missing `pkt_pts_time` field we could just accumulate `pkt_duration_time`.  This script was something I just put together quickly for a few files so I don't really use or maintain it anymore.  If you have a general fix that works for you (and probably others) I'd be happy to take a pull request.
