### ISSUE TITLE
force same bitrate scale

### ISSUE THREAD

**Issue by redgrasss** [zeroepoch/plotbitrate#6]
Hi!
I wonder if it would be possible to force a scale for the bitrate?
In case one would look at different encodings of the same file this would help to compare the different bitrate distribution. At the moment the scale of the bitrate always adapts if there is a big change in the bitrate distribution.
Lets say if I would know the minimun and maximum from a first plot could I then add to the command line like -scalemin 0 -scalemax 60000?

Please consider it as a feature request, not like reporting an issue! :)

**Comment by zeroepoch** [comment]
I'll have to look up the options for setting limits in matplotlib but it's definitely possible.
