### ISSUE TITLE
Frames without timestamp cause crash

### ISSUE THREAD

**Issue by utack** [zeroepoch/plotbitrate#7]
Hi,
I have recently encountered a stream with some images that have no timestamp.

Example:
`        <frame media_type="video" stream_index="3" key_frame="1" pkt_size="23754" width="600" height="882" pix_fmt="yuvj444p" pict_type="I" coded_picture_number="0" display_picture_number="0" interlaced_frame="0" top_field_first="0" repeat_pict="0" color_range="pc" color_space="bt470bg" chroma_location="center"/>
`
This happens when frames are attached:
![screenshot_20171029_143818](https://user-images.githubusercontent.com/8551234/32144286-70c3bc4c-bcae-11e7-8a74-af728b7bc34c.png)

According to [ffmpeg docs](https://www.ffmpeg.org/ffprobe-all.html#Stream-specifiers-1) you need to use "V" as stream option instead of "v" from the current "video" option to ignore attachments.
This fixes the problem

Thank you

**Comment by zeroepoch** [comment]
It's annoying that 'A' doesn't also work for audio.  I'll have to change how it sets this option since I was just using the first char from the steam option before.

**Comment by utack** [comment]
Yes, I wanted to leave it up to you if you want to do "audio" "Video" or something that checks for "v" and makes it caps

**Comment by zeroepoch** [comment]
I'll probably just use an if/else to be clear rather than some wierd single line command.  It's going to take me a week or so to get it changed due to other things going on in my life this week.

**Comment by zeroepoch** [comment]
If you get a chance try it out and confirm it's working with your example file.

**Comment by utack** [comment]
Works now, it ignores the attached images and processes the video frames
Thanks for fixing it
