### ISSUE TITLE
[Request] Support unknown frames

### ISSUE THREAD

**Issue by utack** [zeroepoch/plotbitrate#9]
Hi,
could you please consider support for unknown frames.
ffprobe spits them out as
    pict_type="?"  
  
It can happen for fairly new codecs, currently ffmpeg does not know the frame types of AV1 video for example.  
Thanks

**Comment by zeroepoch** [comment]
Would you suggest we map them to "I" frames?  I suppose a "?" frame could be audio as well in some cases?  We'd need to think of a generic way to handle that so someone doesn't get unexpected results.

**Comment by utack** [comment]
I have mapped them to pink, and just left it shown as "?" frame.  
But maybe a more generic method should be implemented, showing these as "Unknown frametype"?

**Comment by zeroepoch** [comment]
If you have a patch for this (coloring pink and "Unknown frametype") it would be great to get a pull request.  I don't have much time these days to maintain this and also I'm not using it myself anymore.

**Comment by utack** [comment]
I only added '?'  
[here](https://github.com/zeroepoch/plotbitrate/blob/master/plotbitrate.py#L209)  
and [here](https://github.com/zeroepoch/plotbitrate/blob/master/plotbitrate.py#L215)  
  
But I think a cleaner solution might be needed, that can handle any kind of frame ffmpeg tells us?

**Comment by zeroepoch** [comment]
Yeah, I'm not sure besides what is there now and ? what other possible options there are.  I agree though it would be nice to not worry about the frametype at all and just have it generate colors on it's own.  Although I think I did it that way to put the smallest on the bottom to not draw over it.  Can't remember exactly why I did that.  A short term solution is to map anything not in the known list to ?.

**Comment by fuwa200fuwa** [comment]
> I only added '?'

Just actual links to the specific commit: "[here](https://github.com/zeroepoch/plotbitrate/blob/4553220ed5132503c0dda777bcc41b83ec866004/plotbitrate.py#L243) and [here](
https://github.com/zeroepoch/plotbitrate/blob/4553220ed5132503c0dda777bcc41b83ec866004/plotbitrate.py#L249)".

**Comment by zeroepoch** [comment]
I don't have any source files to test how this might work.  Do you have an example video file?  That would help to make sure that only those two lines need to change.

**Comment by fuwa200fuwa** [comment]
Well, ffprobe nightly build can recognize AV1 pict_type (maybe even correctly), so unknown frames support going to be less helpful.

Small AV1 sample + plot with ffprobe4.2.2 + plot with ffprobe20200203-1c15111: [av1_sample.zip](https://github.com/zeroepoch/plotbitrate/files/4154299/av1_sample.zip) 

640x480 => 1280x960 with [L306](https://github.com/zeroepoch/plotbitrate/blob/4553220ed5132503c0dda777bcc41b83ec866004/plotbitrate.py#L306): 

    -   matplot.savefig(args.output, format=args.format)
    +   matplot.savefig(args.output, format=args.format, dpi = 200)

**Comment by zeroepoch** [comment]
It looks like @rezun has resolved this issue in his fork at https://github.com/rezun/plotbitrate. Maybe you can give his version a try?

**Comment by zeroepoch** [comment]
The changes from @rezun's branch have been merged into this repo so the latest commit on `master` should now resolve your issue. Closing this issue as resolved. Reopen if you are still seeing an issue.
